// Frontend service catalog — keys must exactly match server-side PRICE_CATALOG keys in server.js.
// The server holds the actual price_... IDs; this file is purely display-facing.
const CART_CATALOG = [
  {
    key: 'standard_service',
    label: 'Standard Service',
    displayPrice: '$97.99',
    cents: 9799,
    description: 'Delivers legal documents within 5–7 business days.',
    image: 'assets/images/prestige-serves-img-8.png',
    maxQty: 10,
  },
  {
    key: 'rush_serve',
    label: 'Rush Serve',
    displayPrice: '$119.99',
    cents: 11999,
    description: 'Service attempts within 3 business days for urgent matters.',
    image: 'assets/images/prestige-serves-img-9.png',
    maxQty: 10,
  },
  {
    key: 'priority_serve',
    label: 'Priority Serve',
    displayPrice: '$149.99',
    cents: 14999,
    description: 'Service attempts within 2 business days.',
    image: 'assets/images/prestige-serves-img-10.png',
    maxQty: 10,
  },
  {
    key: 'emergency_serve',
    label: 'Emergency Serve',
    displayPrice: '$249.99',
    cents: 24999,
    description: 'Same-day service. Requires internal approval.',
    image: 'assets/images/prestige-serves-img-11.png',
    maxQty: 1,
  },
  {
    key: 'skip_trace_standard',
    label: 'Standard Skip Tracing',
    displayPrice: '$75.00',
    cents: 7500,
    description: 'Los Angeles address research — typical turnaround within standard business days.',
    image: 'assets/images/skip-trace-standard.png',
    maxQty: 10,
  },
  {
    key: 'skip_trace_rush',
    label: 'Rush Skip Tracing',
    displayPrice: '$225.00',
    cents: 22500,
    description: 'Same- or next-business-day priority research when deadlines are tight.',
    image: 'assets/images/skip-trace-rush.png',
    maxQty: 10,
  },
  {
    key: 'skip_trace_court_ready',
    label: 'Court Ready Skip Tracing Report',
    displayPrice: '$250.00',
    cents: 25000,
    description: 'Formatted report suitable for filings and documenting due diligence.',
    image: 'assets/images/skip-trace-court-ready.png',
    maxQty: 10,
  },
  {
    key: 'skip_trace_enhanced',
    label: 'Enhanced Trace',
    displayPrice: '$150.00',
    cents: 15000,
    description: 'Deeper research pass for harder locates and more data points.',
    image: 'assets/images/skip-trace-enhanced.png',
    maxQty: 10,
  },
  {
    key: 'skip_trace_business',
    label: 'Business / Agent Verification',
    displayPrice: '$225.00',
    cents: 22500,
    description: 'Confirm registered agent and business address details for lawful service.',
    image: 'assets/images/skip-trace-verification.png',
    maxQty: 10,
  },
  {
    key: 'addon_defendant',
    label: 'Additional Defendant – Same Case',
    displayPrice: '$45.00',
    cents: 4500,
    description: 'For cases with multiple defendants. Add one per additional individual.',
    image: null,
    maxQty: 10,
  },
];
